name: GitHub Actions Demo
on: [push]
jobs:
  PerformTests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn run test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
